server:
  port: 8001

spring:
  application:
    name: hello-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://eureka-peer1:8762/eureka/, http://eureka-peer2:8763/eureka/
